# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: multi-wget
builds:
  - id: multi-wget
    binary: multi-wget
    main: main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

changelog:
  sort: desc

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: guumaster
    name: multi-wget

nfpms:
  - id: multi-wget
    builds:
      - multi-wget
    formats:
      - deb
    vendor: Guumaster
    homepage: https://github.com/guumaster/multi-wget
    maintainer: guumaster <guuweb@gmail.com>
    description: resumable multiple downloads with wget
